# Generated by Django 5.1.4 on 2025-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0003_alter_customuser_phone_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.TextField(blank=True),
        ),
    ]
