# Generated by Django 5.1.4 on 2025-01-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='passport_photogragh',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
