# Generated by Django 5.1.4 on 2025-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0006_remove_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Account_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Account_number',
            new_name='account_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='BVN',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Local_gov_of_origin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='State_of_origin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='BVN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='local_gov_of_origin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_of_origin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
