# Generated by Django 5.1.4 on 2025-01-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuapp', '0008_websiteconfiguration_alter_userprofile_bvn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='msorg_web_api_key_4',
            field=models.TextField(blank=True, help_text='Enter your APIKEY for your 3rd choice MSORG WEBSITE here if you are using website developed by MSORG else leave blank', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='msorg_web_api_key_5',
            field=models.TextField(blank=True, help_text='Enter your APIKEY for your 3rd choice MSORG WEBSITE here if you are using website developed by MSORG else leave blank', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='msorg_web_url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='msorg_web_url_5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
